name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      EMAILJS_SERVICE_ID: ${{ vars.VITE_EMAILJS_SERVICE_ID || secrets.VITE_EMAILJS_SERVICE_ID }}
      EMAILJS_TEMPLATE_ID: ${{ vars.VITE_EMAILJS_TEMPLATE_ID || secrets.VITE_EMAILJS_TEMPLATE_ID }}
      EMAILJS_PUBLIC_KEY: ${{ vars.VITE_EMAILJS_PUBLIC_KEY || secrets.VITE_EMAILJS_PUBLIC_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create env file
        run: |
          echo "VITE_EMAILJS_SERVICE_ID='$EMAILJS_SERVICE_ID'" > .env
          echo "VITE_EMAILJS_TEMPLATE_ID='$EMAILJS_TEMPLATE_ID'" >> .env
          echo "VITE_EMAILJS_PUBLIC_KEY='$EMAILJS_PUBLIC_KEY'" >> .env
      
      - name: Debug Environment (Safely)
        run: |
          echo "Service ID present in env file? $(grep -q "VITE_EMAILJS_SERVICE_ID=''" .env || grep -q "VITE_EMAILJS_SERVICE_ID='[^']" .env && echo 'Yes' || echo 'No')"
          echo "Template ID present in env file? $(grep -q "VITE_EMAILJS_TEMPLATE_ID=''" .env || grep -q "VITE_EMAILJS_TEMPLATE_ID='[^']" .env && echo 'Yes' || echo 'No')"
          echo "Public Key present in env file? $(grep -q "VITE_EMAILJS_PUBLIC_KEY=''" .env || grep -q "VITE_EMAILJS_PUBLIC_KEY='[^']" .env && echo 'Yes' || echo 'No')"
          echo "Content of .env file (redacted):"
          cat .env | sed 's/=.*/=REDACTED/'
      
      - name: Build
        run: npm run build
        env:
          VITE_EMAILJS_SERVICE_ID: ${{ vars.VITE_EMAILJS_SERVICE_ID || secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ vars.VITE_EMAILJS_TEMPLATE_ID || secrets.VITE_EMAILJS_TEMPLATE_ID }}
          VITE_EMAILJS_PUBLIC_KEY: ${{ vars.VITE_EMAILJS_PUBLIC_KEY || secrets.VITE_EMAILJS_PUBLIC_KEY }}
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages 