name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # Using consistent VITE_EMAILJS_ prefix
      VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
      VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
      VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Debug GitHub Secrets (Safely)
        run: |
          echo "VITE_EMAILJS_SERVICE_ID defined in secrets? $([ -n \"${{ secrets.VITE_EMAILJS_SERVICE_ID }}\" ] && echo 'Yes' || echo 'No')"
          echo "VITE_EMAILJS_TEMPLATE_ID defined in secrets? $([ -n \"${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}\" ] && echo 'Yes' || echo 'No')"
          echo "VITE_EMAILJS_PUBLIC_KEY defined in secrets? $([ -n \"${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}\" ] && echo 'Yes' || echo 'No')"
          echo "Job env variables available? $([ -n \"$VITE_EMAILJS_SERVICE_ID\" ] && [ -n \"$VITE_EMAILJS_TEMPLATE_ID\" ] && [ -n \"$VITE_EMAILJS_PUBLIC_KEY\" ] && echo 'Yes' || echo 'No')"
        
      - name: Create env file
        run: |
          echo "VITE_EMAILJS_SERVICE_ID='$VITE_EMAILJS_SERVICE_ID'" > .env
          echo "VITE_EMAILJS_TEMPLATE_ID='$VITE_EMAILJS_TEMPLATE_ID'" >> .env
          echo "VITE_EMAILJS_PUBLIC_KEY='$VITE_EMAILJS_PUBLIC_KEY'" >> .env
      
      - name: Debug Environment File
        run: |
          echo "Content of .env file (with secrets redacted):"
          cat .env | sed "s/'.*'/'REDACTED'/g"
          echo "Env file has non-empty values? $(grep -v \"=''\" .env | wc -l)"
      
      - name: Build
        run: npm run build
        env:
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
          VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages 